### ISSUE TITLE
React router version upgraded

### ISSUE THREAD

**Issue by Roshankc682** [M-Rahul1/NewsMonkey-React#1]
React router version upgraded

**Comment by MaitriDA** [comment]
Please assign me this issue I have a good experience in react!

**Comment by M-Rahul1** [comment]
already assigned , if they dont take i will assign you.

**Comment by Roshankc682** [comment]
I am doing it @M-Rahul1

**Comment by Roshankc682** [comment]
Done and checked run smoothly with latest react

If any issue i can help
