### ISSUE TITLE
Want updated readme file

### ISSUE THREAD

**Issue by M-Rahul1** [M-Rahul1/NewsMonkey-React#2]
Make changes according to hacktober rules.

**Comment by sirgeorgesawcon** [comment]
Can you be a bit more specific?

**Comment by M-Rahul1** [comment]
Can someone update readme according to hacktoberfest rules.  [https://hacktoberfest.com/participation/#maintainers](url)

**Comment by ShravaniAK** [comment]
i can , please assign to me

**Comment by M-Rahul1** [comment]
Sure
Start with the work . I'll assign you.

**Comment by aryan-jaiswal-12** [comment]
is this issue still open?
