### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by sb-decoder** [M-Rahul1/NewsMonkey-React#4]
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

@M-Rahul1 Do you want this? Then assign this to me.

**Comment by M-Rahul1** [comment]
Yes its needed @sb-decoder .

**Comment by sb-decoder** [comment]
Ok! will add these soon.
